language: python
sudo: false

env:
    global:
        # Undocumented feature of nose-show-skipped.
        NOSE_SHOW_SKIPPED: 1

matrix:
    include:
        - python: 2.7
          env: {TOXENV: py27-test}
        - python: 3.3
          env: {TOXENV: py33-cov, COVERAGE: 1}
        - python: 3.4
          env: {TOXENV: py34-test}
        - python: 3.5
          env: {TOXENV: py35-test}
        - python: pypy
          env: {TOXENV: pypy-test}
        - python: 2.7
          env: {TOXENV: py27-flake8}
        - python: 3.3
          env: {TOXENV: py33-flake8}
        - python: 2.7
          env: {TOXENV: docs}

# Install tox for testing.
install:
    - travis_retry pip install tox

script: tox

# Report coverage to codecov.io.
before_install:
    - "[ ! -z $COVERAGE ] && travis_retry pip install codecov || true"
after_success:
    - "[ ! -z $COVERAGE ] && codecov || true"

cache:
    pip: true
